<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXax5gOx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXax5gOx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXax5gOx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXax5gOx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXax5gOx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xax5gOx',
    'container.build_id' => 'b660bbb5',
    'container.build_time' => 1742573086,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXax5gOx');
